version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adotai_api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/adotai_db?schema=public
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - adotai-network
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm start"

  postgres:
    image: postgres:14
    container_name: adotai_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adotai_db
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 768MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adotai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: 
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=768MB"

volumes:
  postgres_data:

networks:
  adotai-network:
    driver: bridge 