version: '3'

services:
  postgres:
    image: postgres:14
    container_name: adotai_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adotai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adotai-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  adotai-network:
    driver: bridge 